name: wire_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ArcaneArts/wire_cache

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  memcached: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
